### ISSUE TITLE
filename parameter is not used

### ISSUE THREAD

**Issue by krizzzly** [venveo/craft-compress#22]
Hello,

i am using the plugin vor craft cms v3 and try to generate zip files with custom filenames, but i always get `<UID>.zip`

This twig code
`craft.compress.zip(assets, true, filename)`

calls later on in `src/services/Compress.php:104`

`$this->createArchiveAsset($record, $filename);`

but in `src/services/Compress.php:127`

`public function createArchiveAsset(ArchiveRecord $archiveRecord)`

the filename parameter is ignored.

**Comment by Mosnar** [comment]
Right - sorry for the confusion. That feature isn't functional until the Craft 4 version. That's why it's undocumented and a note under the "Caveats & Limitations" section of the README: https://github.com/venveo/craft-compress/tree/develop-v3#caveats--limitations

It's been a few years since the Craft 3 version was built, so I can't remember why I decided to leave the parameter in there. Sorry about that!
